export default {
    logo: 'تالار',
    description: 'عضویت',
    fullnameLabel: 'نام و نام خانوادگی',
    usernameLabel: 'نام کاربری',
    emailLabel: 'ایمیل',
    passwordLabel: 'رمز عبور',
    confirmPasswordLabel: 'تایید رمز عبور',
    rememberMeLabel: 'مرا به خاطر بسپار',
    loginButton: 'ورود به تالار',
    joinButton: 'عضویت',
    notifiUsernameAndPassword: 'لطفا اطلاعات خود را کامل وارد کنید',
    notifiUsername: 'لطفا نام کاربری خود را وارد کنید',
    notifiFullname: 'لطفا نام و نام خانوادگی خود را وارد کنید',
    notifiEmail: 'لطفا ایمیل خود را وارد کند',
    notifiPassword: 'لطفا رمز عبور خود را وارد کنید',
    notifiConfirmPassword: 'لطفا رمز عبور خود را تایید کنید',
    notifiPasswordAndConfirmPassword: 'رمز عبور و رمز تایید شده آن با هم برابر نیست',
}